export enum UpdateType {
  CALLBACK_QUERY = 'CALLBACK_QUERY',
  CHANNEL_POST = 'CHANNEL_POST',
  CHAT_JOIN_REQUEST = 'CHAT_JOIN_REQUEST',
  CHAT_MEMBER = 'CHAT_MEMBER',
  CHOSEN_INLINE_RESULT = 'CHOSEN_INLINE_RESULT',
  DOCUMENT = 'DOCUMENT',
  EDITED_CHANNEL_POST = 'EDITED_CHANNEL_POST',
  EDITED_MESSAGE = 'EDITED_MESSAGE',
  INLINE_QUERY = 'INLINE_QUERY',
  MESSAGE = 'MESSAGE',
  MY_CHAT_MEMBER = 'MY_CHAT_MEMBER',
  POLL = 'POLL',
  POLL_ANSWER = 'POLL_ANSWER',
  PRE_CHECKOUT_QUERY = 'PRE_CHECKOUT_QUERY',
  REPLY_TO_MESSAGE = 'REPLY_TO_MESSAGE',
  SHIPPING_QUERY = 'SHIPPING_QUERY',
  START = 'START'
}
